import firebase, pprint
URL =  firebase.firebaseURL('bitcoinsentiment')
print firebase.get(URL)



json1 = {'13k': {'neg': 1, 'neut': 0, 'pos': 0},
 '3': {'neg': 0, 'neut': 0, 'pos': 1},
 '354': {'neg': 0, 'neut': 0, 'pos': 1},
 '608': {'neg': 0, 'neut': 0, 'pos': 1},
 'ascending': {'neg': 0, 'neut': 1, 'pos': 0},
 'bad': {'neg': 1, 'neut': 0, 'pos': 0},
 'beat': {'neg': 0, 'neut': 1, 'pos': 0},
 'bitcoin': {'neg': 1, 'neut': 1, 'pos': 6},
 'breakout': {'neg': 0, 'neut': 1, 'pos': 0},
 'breaks': {'neg': 0, 'neut': 0, 'pos': 1},
 'brexit': {'neg': 0, 'neut': 0, 'pos': 1},
 'btcusd': {'neg': 0, 'neut': 1, 'pos': 0},
 'bullish': {'neg': 0, 'neut': 1, 'pos': 2},
 'china': {'neg': 0, 'neut': 0, 'pos': 1},
 'coming': {'neg': 0, 'neut': 0, 'pos': 1},
 'continues': {'neg': 0, 'neut': 0, 'pos': 1},
 'contract': {'neg': 0, 'neut': 0, 'pos': 1},
 'contracts': {'neg': 0, 'neut': 0, 'pos': 1},
 'couple': {'neg': 0, 'neut': 1, 'pos': 0},
 'cryptsy': {'neg': 1, 'neut': 0, 'pos': 0},
 'digital': {'neg': 0, 'neut': 0, 'pos': 1},
 'emphasis': {'neg': 0, 'neut': 0, 'pos': 1},
 'ethereum': {'neg': 0, 'neut': 0, 'pos': 1},
 'eu': {'neg': 0, 'neut': 0, 'pos': 1},
 'finishing': {'neg': 0, 'neut': 1, 'pos': 0},
 'future': {'neg': 0, 'neut': 0, 'pos': 1},
 'goes': {'neg': 0, 'neut': 0, 'pos': 1},
 'good': {'neg': 0, 'neut': 0, 'pos': 1},
 'happy': {'neg': 0, 'neut': 0, 'pos': 1},
 'higher': {'neg': 0, 'neut': 0, 'pos': 1},
 'hk': {'neg': 0, 'neut': 0, 'pos': 1},
 'hold': {'neg': 1, 'neut': 0, 'pos': 0},
 'holder': {'neg': 0, 'neut': 0, 'pos': 1},
 'hours': {'neg': 0, 'neut': 1, 'pos': 0},
 'impressive': {'neg': 0, 'neut': 0, 'pos': 1},
 'increased': {'neg': 0, 'neut': 0, 'pos': 1},
 'indicators': {'neg': 0, 'neut': 0, 'pos': 2},
 'leads': {'neg': 0, 'neut': 0, 'pos': 1},
 'max': {'neg': 1, 'neut': 0, 'pos': 0},
 'may': {'neg': 0, 'neut': 0, 'pos': 2},
 'news': {'neg': 1, 'neut': 0, 'pos': 0},
 'nigeria': {'neg': 0, 'neut': 0, 'pos': 1},
 'okcoin': {'neg': 0, 'neut': 0, 'pos': 1},
 'phase': {'neg': 0, 'neut': 1, 'pos': 0},
 'position': {'neg': 0, 'neut': 0, 'pos': 1},
 'pretend': {'neg': 0, 'neut': 0, 'pos': 1},
 'price': {'neg': 0, 'neut': 0, 'pos': 2},
 'removed': {'neg': 1, 'neut': 0, 'pos': 0},
 'roundtable': {'neg': 0, 'neut': 0, 'pos': 1},
 'security': {'neg': 0, 'neut': 0, 'pos': 1},
 'seems': {'neg': 1, 'neut': 0, 'pos': 0},
 'send': {'neg': 0, 'neut': 0, 'pos': 1},
 'sideways': {'neg': 0, 'neut': 0, 'pos': 1},
 'site': {'neg': 1, 'neut': 0, 'pos': 0},
 'stop': {'neg': 0, 'neut': 0, 'pos': 1},
 'supports': {'neg': 0, 'neut': 0, 'pos': 1},
 'take': {'neg': 0, 'neut': 0, 'pos': 1},
 'top': {'neg': 0, 'neut': 0, 'pos': 1},
 'trade': {'neg': 1, 'neut': 0, 'pos': 0},
 'trading': {'neg': 0, 'neut': 1, 'pos': 0},
 'trend': {'neg': 0, 'neut': 0, 'pos': 1},
 'tries': {'neg': 0, 'neut': 0, 'pos': 1},
 'users': {'neg': 1, 'neut': 0, 'pos': 0},
 'via': {'neg': 0, 'neut': 0, 'pos': 1}}


# firebase.put(URL, json1)
a = firebase.get(URL + 'u/via')

